export type Service = {
  slug: string;
  name: string;
  shortName: string;
  title: string;
  description: string;
  startingPrice?: number;
  problems: string[];
  features: string[];
  related: string[];
};

export const services: Service[] = [
  {slug:'computer-repair',name:'Computer Repair',shortName:'Computer Repair',title:'Computer Repair Waterbury CT | PC & Laptop Repair',description:'Desktop, laptop, all-in-one and custom PC diagnostics, repair, upgrades and troubleshooting in Waterbury and surrounding Connecticut communities.',startingPrice:120,problems:['Slow computer','Blue screens and crashes','Won’t turn on or boot','Overheating and loud fans','SSD, HDD, RAM or power issues'],features:['Windows and hardware diagnostics','SSD and RAM upgrades','BIOS/UEFI troubleshooting','Custom and gaming PC builds','Performance optimization'],related:['data-recovery','gaming-systems','virus-software','electronics-repair']},
  {slug:'phone-repair',name:'Phone & Tablet Repair',shortName:'Phone Repair',title:'Phone Repair Waterbury CT | Screen & Battery Service',description:'Phone and tablet diagnostics for supported iPhone, Android and tablet hardware.',startingPrice:100,problems:['Cracked screen','Battery drains quickly','Won’t charge','Charging port damage','Water-damage symptoms'],features:['Screen and battery service','Charging-port assessment','Water-damage diagnostics','Device troubleshooting','Repair-or-replace guidance'],related:['electronics-repair','data-recovery','computer-repair']},
  {slug:'gaming-systems',name:'Gaming PC & Console Repair',shortName:'Gaming Systems',title:'Gaming PC & Console Repair Waterbury CT',description:'Gaming PC builds, console diagnostics, upgrades, cleaning, thermals and supported hardware repair.',startingPrice:125,problems:['Console won’t power on','HDMI problems','Overheating','Slow game loading','PC performance problems'],features:['Custom gaming PC builds','GPU, RAM and SSD upgrades','Console diagnostics','Cooling and cleaning','Performance optimization'],related:['computer-repair','electronics-repair','data-recovery']},
  {slug:'data-recovery',name:'Data Recovery',shortName:'Data Recovery',title:'Data Recovery Waterbury CT | HDD, SSD, USB & SD',description:'Assessment and recovery support for deleted, formatted, inaccessible or failed storage. Recovery is never guaranteed.',startingPrice:150,problems:['Deleted files','Formatted drive','Failing HDD','Inaccessible SSD','USB or SD card failure'],features:['Logical recovery assessment','HDD/SSD evaluation','USB and SD media assessment','Backup and migration planning','Recovery-first handling guidance'],related:['computer-repair','business-it','specialized-services']},
  {slug:'networking-cabling',name:'Networking & Cabling',shortName:'Networking',title:'Networking & Cat6 Waterbury CT | Wi-Fi & Business Networks',description:'Wi-Fi, router, switch, access-point and structured-cabling support for homes and small businesses.',startingPrice:200,problems:['Slow Wi-Fi','Dropped connections','Dead zones','Network configuration problems','Messy or inadequate cabling'],features:['Wi-Fi setup','Router and switch configuration','Access points','Cat5e/Cat6 infrastructure','Network troubleshooting'],related:['business-it','pos-printer','audio-systems']},
  {slug:'pos-printer',name:'POS & Printer Support',shortName:'POS & Printers',title:'POS & Printer Repair Waterbury CT | Business Technology',description:'POS, self-checkout, receipt printer, scanner and supported retail technology installation and troubleshooting.',startingPrice:250,problems:['POS offline','Receipt printer failure','Scanner problems','Self-checkout issues','Payment terminal connectivity'],features:['POS troubleshooting','Printer setup','Scanner and cash-drawer support','Self-checkout support','Business technology diagnostics'],related:['business-it','networking-cabling','maintenance-plans']},
  {slug:'virus-software',name:'Virus & Software Support',shortName:'Virus Removal',title:'Virus & Malware Removal Waterbury CT | Computer Cleanup',description:'Virus and malware cleanup, Windows repair, software installation and performance troubleshooting.',startingPrice:100,problems:['Pop-ups','Slow computer after infection','Browser hijacking','Windows errors','Software conflicts'],features:['Malware assessment','Windows troubleshooting','Software installation','Driver support','Performance optimization'],related:['computer-repair','business-it','data-recovery']},
  {slug:'electronics-repair',name:'Electronics Repair',shortName:'Electronics Repair',title:'Electronics Repair Waterbury CT | Board & Port Diagnostics',description:'Electronics diagnostics, soldering, micro-soldering and supported component-level repair assessment.',startingPrice:100,problems:['Broken charging port','HDMI failure','No power','Board damage','Intermittent electronics'],features:['Board diagnostics','Port repair assessment','Soldering and rework','Power troubleshooting','Component-level assessment'],related:['phone-repair','gaming-systems','specialized-services']},
  {slug:'business-it',name:'Business IT Services',shortName:'Business IT',title:'Small Business IT Support Waterbury CT | OnyxTech',description:'Workstation support, preventive maintenance, technology planning, POS support and recurring IT services.',startingPrice:150,problems:['Office computer issues','Employee workstation problems','Network downtime','Technology planning gaps','Recurring maintenance needs'],features:['Workstation deployment','Preventive maintenance','IT consulting','Microsoft 365 support','Asset and technology planning'],related:['networking-cabling','pos-printer','maintenance-plans']},
  {slug:'smart-home-security',name:'Smart Home & Security Technology',shortName:'Smart Technology',title:'Smart Home Technology Waterbury CT | OnyxTech',description:'Smart-home technology, cameras and automation support subject to applicable licensing, installation and permit requirements.',startingPrice:150,problems:['Smart device setup','Camera connectivity','Doorbell configuration','Home automation issues','Device integration problems'],features:['Smart device configuration','Camera/NVR technology support','Home automation assistance','Network integration','Troubleshooting'],related:['networking-cabling','audio-systems','electronics-repair']},
  {slug:'audio-systems',name:'Audio Systems',shortName:'Audio Systems',title:'Intercom, Paging & Audio Systems Waterbury CT',description:'Intercom, paging, background music, speaker, amplifier and zone-control technology support.',startingPrice:150,problems:['Intercom not working','Paging issues','Speaker problems','Amplifier issues','Audio zones not working'],features:['Intercom support','Paging systems','Background music','Speaker and amplifier setup','Zone configuration'],related:['networking-cabling','business-it','electronics-repair']},
  {slug:'maintenance-plans',name:'Technology Maintenance Plans',shortName:'Maintenance Plans',title:'Computer Maintenance Plans Waterbury CT | OnyxTech',description:'Recurring technology maintenance for homeowners and small businesses.',startingPrice:99,problems:['Recurring computer problems','Outdated systems','Unmonitored backups','Poor device performance','Preventive maintenance gaps'],features:['Scheduled tune-ups','Hardware health checks','Patch planning','Backup monitoring options','Annual technology review'],related:['business-it','computer-repair','networking-cabling']},
  {slug:'specialized-services',name:'Specialized Technology Services',shortName:'Specialized Services',title:'Advanced Electronics & Technology Services Waterbury CT',description:'Advanced hardware diagnostics, PCB work, solder rework, refurbishment and specialized technology assessments.',startingPrice:150,problems:['Board-level failure','Specialized hardware fault','Industrial PC issue','Advanced recovery need','Repair outside ordinary break/fix'],features:['PCB assessment','Solder rework','BIOS programming assessment','Device refurbishment','Specialized hardware diagnostics'],related:['electronics-repair','data-recovery','computer-repair']}
];

export function getService(slug: string) { return services.find((service) => service.slug === slug); }
