import Link from 'next/link';
import type {Service} from '@/lib/services';

export function ServicePage({service}:{service:Service}){return <main id="main"><section className="serviceHero"><div className="container"><div className="breadcrumbs"><Link href="/">Home</Link> / <Link href="/services">Services</Link> / {service.name}</div><div className="eyebrow">{service.shortName} • Waterbury CT</div><h1>{service.title.replace(' | OnyxTech','')}</h1><p className="pageIntro">{service.description}</p><div className="actions"><Link className="btn" href={`/booking?service=${service.slug}`}>Book This Service</Link><a className="btn secondary" href="tel:+12038198645">Call 203-819-8645</a></div></div></section>
<section><div className="container two"><div className="card"><h2>Common Problems We Handle</h2><ul className="checklist">{service.problems.map(p=><li key={p}>{p}</li>)}</ul></div><div className="card"><h2>What We Can Do</h2><ul className="checklist">{service.features.map(p=><li key={p}>{p}</li>)}</ul>{service.startingPrice&&<><p className="price">Starting at ${service.startingPrice}</p><p className="small">Starting price only. Final pricing depends on diagnosis, parts, labor, device condition and service requirements.</p></>}</div></div></section>
<section className="band"><div className="container"><h2>How the Service Works</h2><div className="grid"><div className="card"><h3>1. Tell Us the Problem</h3><p>Describe symptoms, device model and what happened before the issue.</p></div><div className="card"><h3>2. Diagnose</h3><p>We identify likely causes and explain available repair options.</p></div><div className="card"><h3>3. Approve the Work</h3><p>Repair proceeds after scope and pricing are confirmed.</p></div></div></div></section>
<section><div className="container"><h2>Frequently Asked Questions</h2><div className="faq"><details><summary>How much does {service.name.toLowerCase()} cost?</summary><p>{service.startingPrice?`Service starts at $${service.startingPrice}, but the final price depends on the specific problem, parts and labor.`:'Pricing depends on the equipment and diagnosis. Request service for a current estimate.'}</p></details><details><summary>Do you serve Waterbury and nearby Connecticut towns?</summary><p>Yes. OnyxTech is centered in Waterbury and may serve surrounding communities including Naugatuck, Watertown, Southbury, Meriden, Oxford and Milford depending on service and availability.</p></details><details><summary>Can I book before knowing exactly what is wrong?</summary><p>Yes. Choose this service and describe the symptoms. Diagnosis can determine the appropriate repair path.</p></details></div></div></section>
<section><div className="container"><h2>Related OnyxTech Services</h2><div className="service-nav actions">{service.related.map(slug=><Link className="btn secondary" key={slug} href={`/services/${slug}`}>{slug.replaceAll('-',' ')}</Link>)}</div></div></section>
<section className="cta"><div className="container"><h2>Ready to Get Started?</h2><p>Tell OnyxTech what is happening and request service.</p><Link className="btn" href={`/booking?service=${service.slug}`}>Book {service.shortName}</Link></div></section></main>}
